version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          #The name attribute provides useful organizational information when returning warnings, errors, and output.
          #The name should be meaningful to you as an action within your build process
          name: "Say-Hello"
          # The initial pipe, |, indicates that there will be more than one line of shell commands.
          command: |
            echo "Hello!""
            echo "Hows it going!"
      - run:
          command: |
            ls -al
            echo 'here it is!'

workflows:
  say-workflow:
    jobs:
      - say-hello
