version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say-Hello"
          command: |
            echo 'Hello!'

workflows:
  say-workflow:
    jobs:
      -  say-hello